config/urls.py
from django.contrib import admin
from django.urls import path
from pybo.views import base_views, question_views, answer_views, comment_views

# --- [추가 import 부분 ] --- #
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),

    # --- [들어온 URL요청을 각 앱.urls로 맵핑하기] --- #
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
# --- [ config.urls -> pybo.urls -> pybo.views를 위한 URL패턴 설정 ] --- #
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('qusetion/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    
    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/qusetion/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# --- [ 모델 정의하기] --- #


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, on_delete= models.CASCADE, null=True, blank=True)
    answer = models.ForeignKey(Answer, on_delete= models.CASCADE, null=True, blank=True)

pybo/forms.py
from django import forms  # 장고의 기본 폼형식
from pybo.models import Question, Answer, Comment
# 모델 폼, 연결된 모델의 데이터를 저장할 수 있게된다. Class Meta라는 내부클래스가 필수이다.


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

# 답변 작성하기함수
@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # 추가한 속성 author 적용
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


# 답변 수정하기 함수
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    '''
    답변 수정
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    
    # 작성자가 아닐경우
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id = answer.question.id)
    
    # 작성자일 경우
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id = answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


# 답변 삭제하기 함수
@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    '''
    Pybo 답변삭제
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다!')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    '''
    Pybo 목록 출력
    '''
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 기본페이지
    kw = request.GET.get('kw', '') # 기본검색어
    so = request.GET.get('so', 'recent') # 기본정렬

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:   #recent
        question_list = Question.objects.order_by('-create_date')

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 한 페이지당 10개의 글을 페이징 객체로 변환하기.
    page_obj = paginator.get_page(page)  # paginator로 page 객체 불러오기

    context = {'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}
    return render(request, 'pybo/question_list.html', context)

# 질문 상세보기함수
def detail(request, question_id):
    '''
    Pybo 내용 출력
    '''
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment

# 질문글 댓글 작성하기 함수
@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    '''
    Pybo 질문글의 댓글작성
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id = comment.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


# 질문글 댓글 수정하기 함수
@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    '''
    Pybo 질문글의 댓글수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    # 댓글 작성자가 아닐경우
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다!')
        return redirect('pybo:detail', question_id = comment.question.id)

    # 댓글작성자인데, 전송방식이 'POST'방식일 경우
    if request.method =='POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


# 질문글 댓글 삭제하기 함수
@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    '''
    Pybo 질문글의 댓글삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    # 댓글 작성자가 아닐경우
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다!')
        return redirect('pybo:detail', question_id = comment.answer.question.id)
    
    # 댓글 작성자일 경우
    else:
        comment.delete()
    return redirect('pybo:detail', question_id = comment.question.id)


# 답글 댓글 작성하기 함수
@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    '''
    Pybo 답글의 댓글작성
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id = comment.answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


# 답글 댓글 수정하기 함수
@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    '''
    Pybo 답글의 댓글수정
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    # 댓글 작성자가 아닐경우
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다!')
        return redirect('pybo:detail', question_id = comment.answer.question.id)

    # 댓글 작성자인데, 전송방식이 'POST'방식일 경우
    if request.method == 'POST':
        form = CommentForm(request.POST, instance = comment)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id = comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance = comment)
    context = {'form':form}
    return render(request, 'pybo/comment_form.html', context)


# 답글 댓글 삭제하기 함수
@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    '''
    Pybo 답글의 댓글삭제
    '''
    comment = get_object_or_404(Comment, pk=comment_id)
    # 댓글 작성자가 아닐경우
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다!')
        return redirect('pybo:detail', question_id = comment.answer.question.id)
    
    # 댓글 작성자일 경우
    else:
        comment.delete()
    return redirect('pybo:detail', question_id = comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


#질문 작성하기함수
@login_required(login_url='common:login')
def question_create(request):
    '''
    pybo 질문 등록
    '''
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


# 질문 수정하기 함수
@login_required(login_url='common:login')
def question_modify(request, question_id):
    '''
    질문 수정
    '''
    question = get_object_or_404(Question, pk=question_id)
    
    # 작성자가 아닐경우
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다!')
        return redirect('pybo:detail', question_id = question.id)
    
    # 작성자일 경우
    if request.method=='POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id = question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form' : form}
    return render(request, 'pybo/question_form.html', context)


# 질문 삭제하기 함수
@login_required(login_url='common:login')
def question_delete(request, question_id):
    '''
    질문 삭제
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다!')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer

# 질문글 추천 함수
@login_required(login_url='common:login')
def vote_question(request, question_id):
    '''
    Pybo 질문추천등록
    '''
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

# 답글 추천 함수
@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    '''
    Pybo 답글 추천등록
    '''
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}

<div class='container my-3'>
    <form method='post' class='post-form'>
        <!-- 'POST'방식 보안 토큰 -->
        {% csrf_token %}
        <!-- 에러부분 -->
        {% include 'form_errors.html' %}
        
        <div class='form-group'>
            <label for='content'>답변내용</label>
            <textarea class='form-control' name='content' id='content' rows='10'>{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type='submit' class='btn btn-primary'>저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
    <div class='container my-3'>
        <h5 class='border-bottom pb-2'>댓글 등록하기</h5>
        <form method="POST" class='post-form my-3'>
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <div class='form-group'>
                <label for='content'>댓글내용</label>
                <textarea class='form-control' name='content' id='content' row='3'>{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type='submit' class='btn btn-primary'>저장하기</button>
        </form>
    </div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3"> <!-- html 포멧 작성 시작 -->
        
        {% if messages %} <!-- 사용자오류 표시 -->
            <div class="alert alert-danger my-3" role="alert">
                {% for message in messages %}
                    <strong>{{ message.tags }}</strong>
                    <ul><li>{{ message.message }}</li></ul>
                {% endfor %}
            </div>
        {% endif %} <!-- 사용자오류 끝 -->

        <!-- 질문 제목 -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>


        <div class="row my-3">
            <div class="col-1"> <!-- 추천영역 -->
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div> <!-- 추천수 카운트 -->
                <a href="#" data-uri="{% url 'pybo:vote_question' question.id  %}"class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a> <!-- 추천 버튼 -->
            </div> <!-- 추천영역 끝 -->


            <div class="col-11"> <!-- 질문영역 시작 -->
                <div class="card">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div> <!-- 질문 내용 -->
                        <div class="d-flex justify-content-end">

                            {% if question.modify_date %}   <!-- 질문을 수정한적이 있을경우 시작 -->
                                <div class="badge badge-light p-2 text-left mx-3">
                                    <div class="mb-2">modified at</div>
                                    <div>{{ question.modify_date }}</div>
                                </div>
                            {% endif %} <!-- 질문을 수정한적이 있을경우 끝-->

                            <div class="badge badge-light p-2 text-left"> <!-- 질문 작성자 정보 시작 -->
                                <div class="mb-2">{{ question.author.username }}</div>
                                <div>{{ question.create_date }}</div>
                            </div> <!-- 질문 작성자 정보 끝 -->
                        </div>

                        {% if request.user == question.author %} <!-- 사용자와 질문 작성자가 같을경우 버튼 활성화 시작 -->
                            <div class="my-3">
                                <a href="{% url 'pybo:question_modify' question.id  %}"class="btn btn-sm btn-outline-secondary">수정</a>
                                <a href="#" class="delete btn btn-sm btn-outline-secondary"data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                            </div>
                        {% endif %} <!-- 사용자와 질문 작성자가 같을경우 버튼 활성화 끝 -->


                        {% if question.comment_set.count > 0 %} <!-- 질문 댓글 시작 -->
                            <div class="mt-3">

                                {% for comment in question.comment_set.all %} <!-- 질문의 모든 댓글 보여주기 시작 -->
                                    <a name='comment_{{ comment.id }}'></a> <!-- 댓글 앵커 생성 -->
                                    <div class="comment py-2 text-muted">
                                        <span style="white-space: pre-line;">{{ comment.content }}</span>
                                        <span>
                                            - {{ comment.author }}, {{ comment.create_date }}
                                            {% if comment.modify_date %}
                                            (수정:{{ comment.modify_date }})
                                            {% endif %}
                                        </span>

                                        {% if request.user == comment.author %} <!-- 사용자와 댓글 작성자가 같을경우 버튼 활성화 시작 -->
                                            <a href="{% url 'pybo:comment_modify_question' comment.id  %}" class="small">수정</a>,
                                            <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id  %}">삭제</a>
                                        {% endif %} <!-- 사용자와 댓글 작성자가 같을경우 버튼 활성화 시작 -->

                                    </div>
                                {% endfor %} <!-- 질문의 모든 댓글 보여주기 끝 -->

                            </div>
                        {% endif %} <!-- 질문 댓글 끝 -->

                        <div> <!-- 댓글 달기 버튼 -->
                            <a href="{% url 'pybo:comment_create_question' question.id  %}"class="small"><small>댓글 추가 ..</small></a>
                        </div>
                        <!-- 질문 댓글 끝 -->
                    </div>
                </div>
            </div> <!-- 질문 영역 끝-->

        </div>

        <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5> <!-- 답변 갯수 카운트 -->
        {% for answer in question.answer_set.all %} <!-- 모든 답글 보여주기 시작 -->
            <a name='answer_{{ answer.id }}'></a> <!-- 답글 앵커 생성 -->
            <div class="row my-3">

                <div class="col-1"> <!-- 추천영역 시작 -->
                    <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
                    <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
                </div> <!-- 추천영역 끝-->

                <div class="col-11"> <!-- 답변표시 영역 시작 -->
                    <div class="card">
                        <div class="card-body">
                            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                                <div class="d-flex justify-content-end">

                                    {% if answer.modify_date %} <!-- 답글을 수정한적이 있는경우 시작 -->
                                        <div class="badge badge-light p-2 text-left mx-3">
                                            <div class="mb-2">modified at</div>
                                            <div>{{ answer.modify_date }}</div>
                                        </div>
                                    {% endif %} <!-- 답글을 수정한적이 있는경우 끝 -->

                                    <div class="badge badge-light p-2 text-left"> <!-- 답글 작성자 정보 시작-->
                                        <div class="mb-2">{{ answer.author.username }}</div>
                                        <div>{{ answer.create_date }}</div>
                                    </div> <!-- 답글 작성자 정보 끝 -->
                                </div>
                            {% if request.user == answer.author %} <!-- 사용자와 답글 작성자가 같을경우 버튼 활성화 시작 -->
                                <div class="my-3">
                                    <a href="{% url 'pybo:answer_modify' answer.id  %}"class="btn btn-sm btn-outline-secondary">수정</a>
                                    <a href="#" class="delete btn btn-sm btn-outline-secondary "data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                                </div>
                            {% endif %} <!-- 사용자와 답글 작성자가 같을경우 버튼 활성화 시작 -->

                            {% if answer.comment_set.count > 0 %} <!-- 해당 답글에 댓글이 0개이상 있을경우 시작 -->
                                <div class="mt-3">

                                    {% for comment in answer.comment_set.all %} <!-- 모든 댓글을 보여주기 시작 -->
                                        <div class="comment py-2 text-muted">
                                            <span style="white-space: pre-line;">{{ comment.content }}</span> <!-- 댓글 내용 -->
                                            <span>
                                                - {{ comment.author }}, {{ comment.create_date }}
                                                {% if comment.modify_date %}
                                                (수정:{{ comment.modify_date }})
                                                {% endif %}
                                            </span>
                                            
                                            {% if request.user == comment.author %} <!-- 사용자가 댓글작성자일 경우 버튼 활성화 시작 -->
                                                <a href="{% url 'pybo:comment_modify_answer' comment.id  %}" class="small">수정</a>,
                                                <a href="#" class="small delete"data-uri="{% url 'pybo:comment_delete_answer' comment.id  %}">삭제</a>
                                            {% endif %} <!-- 사용자가 댓글작성자일 경우 버튼 활성화 끝 -->

                                        </div>
                                    {% endfor %} <!-- 모든 댓글을 보여주기 끝 -->

                                </div>
                            {% endif %} <!-- 해당 답글에 댓글이 0개이상 있을경우 끝-->

                            <div>
                                <a href="{% url 'pybo:comment_create_answer' answer.id  %}"class="small"><small>댓글 추가 ..</small></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %} <!-- 모든 답글 보여주기 끝 -->


        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3"> <!-- 답글 작성영역 시작 -->
            {% csrf_token %}

            {% if form.errors %} <!-- 답글작성 영역 에러 시작-->
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %} <!-- 답글작성 영역 에러 끝 -->

            <div class="form-group"> <!-- 답글작성 textarea 활성화/비활성화 시작-->
                <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"> {% if not user.is_authenticated %} 로그인 후 이용해주세요. {% endif %} </textarea>
            </div> <!-- 답글작성 textarea 활성화/비활성화 시작-->

            <input type="submit" value="답변등록" class="btn btn-primary">
        </form> <!-- 답글 작성영역 끝 -->
    </div> <!-- html 포멧 작성 끝 -->

<!-- 스크립트 코드 -->
{% endblock %}
    {% block script %}
    <script type='text/javascript'>
    $(document).ready(function(){
        // 삭제팝업 스크립트
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });

        // 추천팝업 스크립트
        $(".recommend").on('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
    </script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<!--- base.html 내부 구현부분 시작 --->
<div class='container'>
    <h5 class='my-3 border-bottom pb-2'> 질문등록 </h5>
    <form method='post' class='post-form my-3'>
        
        <!--- POST방식을 이용할때 이용하는 장고기본 미들웨이 --->
        {% csrf_token %}

        <!--- 오류표시 시작-->
        {% if form.errors %}
            <div class='alert alert-danger' role='alert'>
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!--- 오류표시 끝 --->

        <!--- 제목부분(만약 아무것도 입력안할시 None이 아니라 공백으로) --->
        <div class='form-group'>
            <label for='subject'>제목</label>
            <input type='text' class='form-control' name='subject' id='subject' value='{{ form.subject.value|default_if_none:"" }}'>
        </div>

        <!--- 내용부분(만약 아무것도 입력안할시 None이 아니라 공백으로) --->
        <div class='form-group'>
            <label for='content'>내용</label>
            <textarea class='form-control' name='content' id='content' rows='10'>{{ form.content.value|default_if_none:"" }}</textarea>
        </div>
        <button type='submit' class='btn btn-primary'> 저장하기 </button>
    </form>
</div>
{% endblock %}
<!--- base.html 내부 구협부분 끝 --->