common/urls.py
# --- [ config.urls -> common.urls -> pybo.views를 위한 URL패턴 설정 ] --- #
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from pybo.views import base_views, question_views, answer_views, comment_views

# --- [추가 import 부분 ] --- #
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),

    # --- [들어온 URL요청을 각 앱.urls로 맵핑하기] --- #
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
# --- [ config.urls -> pybo.urls -> pybo.views를 위한 URL패턴 설정 ] --- #
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('qusetion/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    
    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/qusetion/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question


def index(request):
    '''
    Pybo 목록 출력
    '''
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 기본페이지
    kw = request.GET.get('kw', '') # 기본검색어
    so = request.GET.get('so', 'recent') # 기본정렬

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:   #recent
        question_list = Question.objects.order_by('-create_date')

    # 검색
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 한 페이지당 10개의 글을 페이징 객체로 변환하기.
    page_obj = paginator.get_page(page)  # paginator로 page 객체 불러오기

    context = {'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}
    return render(request, 'pybo/question_list.html', context)

# 질문 상세보기함수
def detail(request, question_id):
    '''
    Pybo 내용 출력
    '''
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang='ko'>
    <head>
        <!-- Required meta tags -->
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <!-- Bootstrap CSS -->
        <link rel='stylesheet' type='text/css' href='{% static "css/bootstrap.min.css" %}'>
        <!-- Pybo CSS 미사용 -->
        <link rel='stylesheet' type='text/css' href='{% static "style.css" %}'>
        <title> 여기는 Pybo! </title>
    </head>

    <body>
        <!--- 네비게이션 바 부분 include --->
        {% include 'navbar.html' %}

        <!--- 상속받는 템플릿의 구현부분--->
        {% block content %}
        {% endblock %}

        <!-- JQuery JS-->
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <!-- Bootstrap JS-->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- 자바스크립트 부분 -->
        {% block script %}
        {% endblock %}
    </body>
</html>

templates/errors.html
<!--- 첫 로그인 에러시 이동화면 html --->
{% extends 'base.html' %}
{% block content %}
<div class='container my-3'>
    <form method='post' class='post-form' action='{% url "common:login" %}'>
        {% csrf_token %}
        {% include 'form_errors.html' %}
        <div class='form-group'>
            <label for='username'> 사용자 ID </label>
            <input type='text' class='form-control' name='username' id='username' value=' {{ form.username.value|default_if_none:"" }} '/>
        </div>
        <div class='form-group'>
            <label for='password'> 비밀번호 </label>
            <input type='password' class='form-control' name='username' id='username' value=' {{ form.username.value|default_if_none:"" }}'/>
        </div>
        <button type='submit' class='btn btn-primary'> 로그인 </button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!--- 로그인 오류 발생시 알림 html --->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class='alert alert-danger'>
                <strong> {{ field.label }}</strong>
                {{ field.errors }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class='alert alert-danger'>
            <strong>{{ error }}</strong>
            {{ field.errors }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!--- 네비게이션바 시작 --->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">

    <!--- Pybo라고 쓰여있는 localhost:8000/index로 가는 링크 --->
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>

    <!--- 아이콘 이미지를 이용한 버튼 형식의 메뉴 네비게이션 --->
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!---로그인/로그아웃 기능 링크(네비게이션 종속형태)--->
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="nav bar-nav">
            <li class="nav-item ">
                <!-- 로그인 상태일시 -->
                {% if user.is_authenticated %}
                    <a class='nav-link' href="{% url 'common:logout' %}"> {{ user.username }} (로그아웃) </a>
                {% else %}
                <!-- 비로그인 상태일시 -->
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
<!--- 네비게이션바 끝 --->